baseurl = "https://jhonatanbds.github.io/portfolio-vis"
languageCode = "pt-br"
title = "Visualização de Informação"
theme = "hugo-steam-theme"
disqusShortname = "spf13"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 10

[params]
	title = "Visualização de Informação"
	subtitle = "portfolio de visualizações referentes à disciplina"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themecolor = "green"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Jhonatan Batista"
	bio = "Computer Science undergraduate at UFCG"
	description = "Your description of the blog"
	
	# Link your social networks (optional)
	location = ""
	twitter = "jbatistakkk"
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "jhonatanbds"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
